name: Build
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
      - name: Install apt packages
        run: sudo apt-get install -y debhelper
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Package
        run: fakeroot debian/rules binary
      - name: Get package name
        id: get-package-name
        run: |
          echo "name=$(basename ../*.deb)" >> "$GITHUB_OUTPUT"
      - name: Upload build output
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ steps.get-package-name.outputs.name }}
          path: ${{ github.workspace }}/../${{ steps.get-package-name.outputs.name }}
