name: Build
on:
  pull_request:
  workflow_call:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v
      - name: Package
        run: |
          package_file=$(./.github/workflows/package.sh)
          echo "package_file=$package_file" >> "$GITHUB_ENV"
      - name: Upload build output
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ env.package_file }}
          path: ${{ env.package_file }}
