name: Build
on:
  pull_request:
  workflow_call:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v
      - name: Package
        run: |
          package_file=$(./.github/workflows/package.sh)
          echo "package_file=$package_file" >> "$GITHUB_ENV"
      - name: Upload build output
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ env.package_file }}
          path: ${{ env.package_file }}
